# Generated by Django 5.2 on 2025-05-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SUPPLEMENTS', 'Suplementos'), ('EQUIPMENT', 'Equipo de gimnasio'), ('APPAREL', 'Ropa deportiva'), ('ACCESSORIES', 'Accesorios')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
